### ISSUE TITLE
Missing items: [Mark of Conquest]

### ISSUE THREAD

**Issue by i1Spook** [wowsims/tbc#1089]
Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
https://tbc.wowhead.com/item=27921/mark-of-conquest

**Comment by jimmyt857** [comment]
Thanks for the report! This item is intentionally left out though, as its below the ilvl cutoff we use. We don't want to have too many items in the sim because they generally aren't used and it increases load times.

You can use the Bonus Stats section to give yourself custom stats in place of them item though!
