### ISSUE TITLE
Hit Food VS agi food overvalue

### ISSUE THREAD

**Issue by Ootor** [wowsims/tbc#356]
**Describe the bug**
Hello! First anomaly I have found with this sim.  I am running my current gear set which nets me 74 hit rating. We do have improved FF but I still need 20 hit to be about 6% hit.  So I run hit food, and other my raid factors I hit about 2860 DPS.  When The only thing I change is the food to 20 agi food my DPS should go down (not hit cap) but instead it shoots up to 2923 DPS.  

**To Reproduce**
1. Go to any BM preset
2. Click on hit food
3. Sim it
4. click on agi food
5. sim it
6. Value of hit food might be too high?

**Expected behavior**
I expected the DPS increase to be maybe 5-10 DPS with the food switch alone, not 20-60.  

**Sim Links and Screenshots**
Link to my Sim
https://wowsims.github.io/tbc/hunter/#eJzlUkFLG0EYzft2Z9ksBoY0h21AiEsPoVA6u3FBe+juTQ89xJtHe6gg9FB7Sj2F9mI9SI5JEOmxUijeigR7qIe2ehBUVLChDUSxEUppBQXb0m+y9Ff0Y/iYee/N+x7DOKaNImUzNtVBFarCrIHyP82nsMoP7z958NhOS8pvw5Fy/QzufBeetdlG4zccU27/0fjyD7i/3jD+7gq8nIzcWIe795w841MLzjXZ4osbLXjpixYOjrDV1prFHtydf5qMbLBJ9RkftcOAPOyxHzOatOUr1n4+0bPqbFVbZe4i4Ux53tW929N9uaP7+2M9dIXvLLEynbhocYqtGmywvwZvcJXMD2S9JHwh8Z3EJYmKUYUxD9SBm6dI/Sc1Z9uQ5NII7kw6N3gPv9nQtRaNlvq1G8UYPzcmEvhrlC3aQsKlgigKRadEI2ZsjKMsJjElHokK8RvyJ3oBkbdsi5VYQCH0A6UC5Yd+qPwgGC75KvRvqVCFDAYqbCLl3Uv3E1Wn46Ek2934ejL0Y5S9nZC5t7FLWU/nLBDnojJNoUIzuddjnbnct2i2r6otxH8BJ5iHZA==

Use pre-set value Ootor 2/8 Demon 1 and Ootor Standard.  Toggle hit food and agi food to see the huge difference

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 98.0.4758.82

**Comment by Ootor** [comment]
Also I would like to note that I think the t5 2pc bonus is somehow being calculated towards DPS.  I am not sure why this is but when I compare DPS with t5 chest/helm only switching out t5 helm for CVoS I see a DPS loss.  If I am only simming with 1 piece of T5 and looking at gear upgrades I am seeing DPS gains again.  Sorry for the limited format of this share.  You can use my settings above to recreate this issue as well.

**Comment by jimmyt857** [comment]
Thanks for reporting this! I think both of your issues are caused by the interaction between mana and viper aspect swapping. Turning off aspect swapping by setting the start value to 0%, or increasing available mana using dark runes, seem to fix the issue.

I think what's happening is that the lower hit rate when using agi food causes you to use fewer Kill Command's, which means less mana usage. This is making the sim able to go longer without swapping to Viper, and it looks like you're right on the edge between having enough mana or not depending on fight length.

Going to leave this thread open for a bit because I found a few small UI bugs while looking at this. Also, I think our aspect swapping causes too much of a dps loss so that's a bug I need to fix as well.

**Comment by Ootor** [comment]
Good deal thanks for the reply.

**Comment by jimmyt857** [comment]
This should be resolved now. Fixed an actual bug causing auto shot delays when aspect swapping, and also improved the AI so it will always swap back to hawk when it has enough mana for the rest of the fight.
