### ISSUE TITLE
Weightstones not working correctly

### ISSUE THREAD

**Issue by jimbus3000** [wowsims/tbc#375]
Getting less DPS using one adamantite weightstone on one of my two weapons, or no stones at all, than I do with both stones equipped. Same gearset. 

[Using this gear set ](https://wowsims.github.io/tbc/hunter/#eJzlUs9LFVEU7jszd7heKi9j5O1BMA0tHkJwZ2xA28xbunzuWuaiXYtw9WwlufEFgguF9wzCZdBGCiIxUsgsW1aEgaKCL0w3DxRfi8TOzCD0P3S4nHPud37fe5QrUSZfSyyAGkCNxuFMg0qvxGN41QcjY/dHpaep9BlK66NNmMk9hN7mEpqnUK7+0Mrw5UOYjd0C56OkXmvBfKuT6tGrHPN+CWFXYeuw+ZJe/QPzpU6hc5p7v+X48QlSF/XGwb9ZXhzAbP/MKjTYY3qBbe3C5uqjvYx3djL+bDfjH/Ne1n7ATE1Q6HXOszzdyhHWmpzl+yLC4A05K0SfiJ4Tdki0SfwmUXN49kmAn6FvHxf+E3okJTQZGsCdEXWTdURzzYwW08H+nL6mFQwdO8MF/Cv1y1JoGApEWVjaJxpwK84QquIu7omHokb8hrxC8xClbt4dGNwoSrXTJwiSKLY2tlESJTaK49v9kU2iWzaxCYOxTeYwqDzlypMGcjkzS5nUr19CCeXIVm9+zT9bXZb1q8HZOSGMuvJCK6OVa0W366l/vcCuvKv4fjZeAB6HqsTdooa/D9GTOA==), simmed with no stones, one stone on one weapon, one stone on other weapon, then no stones and got these DPS results 

Two stones: 2396
One stone (Left): 2452
One stone (right): 2454
No stones: 2433

Expected two stones to be top DPS, one stone on either weapon to be middle, no stones bottom

 - OS: Windows 10
 - Browser: Chrome
 - Version 98.0.4758.82

**Comment by jimmyt857** [comment]
Thanks for the report jumbus!

It turned out we has a very sneaky bug related to the way we use a 'pre-sim' to compute damage averages for each ability, which are then used to calculate the rotation. TLDR, tiny differences in RNG were causing large differences in rotation.

After fixing that issue, the settings you linked seem to be working properly now. Let us know if you spot anything else!
