### ISSUE TITLE
Missing items: Waistguard of Shackled Souls

### ISSUE THREAD

**Issue by erinstrubbe** [wowsims/tbc#384]
Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item: https://tbc.wowhead.com/item=32397/waistguard-of-shackled-souls

**Comment by lologarithm** [comment]
That item is technically in the sim but has 0 EP so it's not showing up. You can just remove the item to simulate it.

**Comment by jimmyt857** [comment]
@lologarithm do you think cases like this might be a good reason to just remove the EP filter? It's perfectly reasonable for someone to want to sim their dps with other gear on, and they should be able to share the full set via linking rather than having to describe that its a shadow resist set (in this case).

**Comment by lologarithm** [comment]
alright, removed the EP filter. All items should now show up.
