### ISSUE TITLE
Missing items: Fel Strength-elixir

### ISSUE THREAD

**Issue by Alaskanhike** [wowsims/tbc#403]
[Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
](https://tbc.wowhead.com/item=31679/fel-strength-elixir)

**Comment by jimmyt857** [comment]
Is this something that people use? I've never heard of anyone using it before, I'm sure you're not the only one but its definitely not a common option.

We have to be careful about adding things like this, because there are quite a few 'uncommon' options and if we added them all it would take up too much screen space and make the UI feel a lot less simple. Do you think its worth the space?

**Comment by Alaskanhike** [comment]
@jimmyt857 I would say it would be a good option when trying to weave demonslaying elixar (better then 25 Str, but it is a bit more expensive then AGI, Mongoose, STR for Enh). Its the best option for Enh shaman other then using flask when not using Demonslaying. In the end, I guess I can turn off my elixir and just put 65 AP extra in the gear options.

**Comment by jimmyt857** [comment]
I think for now using the 'Bonus Stats' feature is the way to go. However, somewhat soon we might be changing the UI for consumables to use dropdowns, and if so that will let us add this without sacrificing any screen space. Will leave this thread open as a reminder for when we do.

**Comment by jimmyt857** [comment]
This has now been added!
