### ISSUE TITLE
[Shadow Priest Sim] Spell hit EP wrong/Spell hit cap wrong

### ISSUE THREAD

**Issue by jvyth** [wowsims/tbc#433]
**Describe the bug**
Hit rating cap is either not correct (should be 16% but seems to be 18% in the sim), or the EP is not correctly calculated.

**To Reproduce**
1. Go to sim link below.
2. Calculate EP values.
3. See that hit rating EP is >1.
4. Remove the -25 hit rating under Bonus Stats and run EP again.
5. Hit rating EP is now ~0.

**Expected behavior**
Hit rating EP should be close to 0 when you have spell hit cap (16%).

**Sim Links and Screenshots**
[Link.](https://wowsims.github.io/tbc/shadow_priest/#eJzFUTtLA0EYzOw9uKyI62mxppBwlRECmxxXWCU/QfwFWmhlIVZqFVIoWolaaApRQRBtrvSBYmERU6goakQJRiPkgRrsRAnuXSr/gA7LsMzON7PsUtVADzF1A4MYQ2hDTUPvHx2aHB43dKaF9kAZy3+Az5Rg6Zs53H6Bqiz37ulXNfDXotQLB5CLGuysAd5IE9rGzmuwgk29eVSogE+7oK3sWsbVH2ApJ35W6hu0gy1VwS8Pf80w9rYNXlwkfsHNvWf+LHn8VPF4YYdI3n/x0u9mCV93PTXvO1arsFpcoqSImiWYQG8ZgX9B3/FfN07JH2VkwKbEgBnh8gmUeZBlaGvQtgAX2i6QBbmAlgceoZWh1YGQtM8h7AgRt4UQdjTqCDvuCCcmJEuSO8eJZRCw4kG/KDWS7MqseDhNmN1NrfMoyYnZLm8AjjCJ2D6eEz/G9mlx)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version 97.0.1

**Comment by jimmyt857** [comment]
Thanks for the report!

EP with hit rating is kinda complicated. The gist is that, past a certain threshold (~80 rating), we calculate hit EP using the dps of your settings compared to the dps with 10 hit rating **subtracted**. This is done to make sure the value stays accurate right up to the hit cap. Unfortunately, as you've seen, it causes this behavior where the EP value doesn't show as 0 until we're 10 rating over the cap.

This isn't ideal but we've gone through a few iterations of hit EP and none really satisfy everything. If you have any suggestions on how you think it could work instead feel free to offer them.

Would like to also note that hit EP is not included in the EP totals for each item in the item selector, for being unreliable due to weirdness like this. The EP should not be taken too seriously anyway, simming actual setups is always more accurate than inferring based on EP.

**Comment by jvyth** [comment]
Thanks for the detailed response.

Ahh, that explains it! Forgive me if I've misunderstood something here, but wouldn't this be remedied if you calculate EP with additional stats rather than subtracted stats? Maybe this is one of the iterations you've mentioned that wasn't perfect.

Good info regarding inclusion in item EP totals! I always use EP as a just an estimate as "oh, spell crit is kinda shit, eh?", rather than absolute values. However, hit being valued when above cap got me thinking!

**Comment by jimmyt857** [comment]
If we did additional instead of subtracted, the EP value would start tapering off before reaching the actual cap. Ideally what we want is for the EP to show the 'full value' always regardless of whether you're over cap, but for now we're settling for 'always the full value up to cap, and a bit higher'.

Going to close this thread because there isn't an issue here, but if you'd like to discuss further feel free to join our discord and chat!
