### ISSUE TITLE
Hunter sim: pet uptime and number of iterations

### ISSUE THREAD

**Issue by Fluffy-phd** [wowsims/tbc#448]
**Describe the bug**
The value of Pet uptime is not being preserved when the page is refreshed. Same goes for the number of Sim iterations.

**To Reproduce**
Set Pet uptime to other than the default value of 100 and/or the number of iterations to other than 3000. Refresh the page

**Expected behavior**
Both values should be preserved.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozzil
 - Version: Cannot find info, cloned 28/02/2022

**Comment by jimmyt857** [comment]
Thanks for the report! Pet uptime seems to be working fine, and iterations was well-known. We didn't want to have iterations be saved because there wasn't a way to 'restore defaults' before. Now that default restoration functionality is finally added I've updated the sim to save other settings like # of iterations.
