### ISSUE TITLE
[Bug] Maintaining Sunder Debuff has much fewer casts than expected

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/tbc#722]
**Describe the bug**
In 180s fight, there are only few sunder armor casts at the beginning of the fight and the sunder debuff never fell off.

**To Reproduce**
1. Enable maintain debuff on sunder armor
2. Go to detailed results
3. Check sunder armor casts number

**Expected behavior**
There should be a lot more casts to maintain sunder armor debuff over 180s.

**Sim Links and Screenshots**
https://wowsims.github.io/tbc/warrior/#eJztUk0oRFEUnu88w3uv1O2xeGbFYzGUum+mqVHKtUPRZGWJMlE2rIbVS6MwM5pm5SfZWloxZeMnIimFoogkS8XGYij3vWcsrC193c4593zf+e5ZXJ3CZBgqlkBhpMiBUkRwFxS6CM6gMjE+NDUyqVYxLXQFnbG1LJlzT7Aqb0pY/oSusa0sWcpZySULGTI/tn1SHr2a7cnO5fy3oIbdyemDHVjaoyfwNfM5Mks3KJvsS82pHCmbaOwt92OQln73z78NFsl8v/02qGCvn27MZUjGUtaNGznSVXbokLmadqsjWa1vuqr9WbJCRSKHMEc4pooHCl5TMKXkFSwpaDmnwD/+FNOqCgGT4pjs0duZ/HHNPtEnbL9oEm1e3u0XnX6nVnT7nWGRwCgGMYA8YARCKoOJenAsoDEa4zzGbTvKI9zmsVZ5kR0ec5Md8agVBKxezbNykqKhbF63suzipMPgPhkvCpOMRiYXdYAuJGhAPpqisaSHl44Jf52C+ALB63x6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 100.0.4896.127

**Comment by jimmyt857** [comment]
This is working as intended! It's because you have Sunder Armor and IEA selected in the 'Debuffs' section.

The Debuff section Sunder Armor represents other players casting sunder; it add a stack of sunder every 1.5s, and those are permanent. This is why it only casts 2 sunders; the other 3 are coming from 'the raid'.

The Debuff section IEA is applied at 10s, after which point the warrior won't even try to cast sunder.
