### ISSUE TITLE
Human Expertise not taken into account on weapon upgrade values.

### ISSUE THREAD

**Issue by brandofriva** [wowsims/tbc#755]
On the warrior SIM it seems to ignore human expertise bonus when looking at weapon upgrade values in the upgrade window e.g.  when I tested all 3 vengeful weapons simmed the same.

**To Reproduce**
1. Take P4 preset
2. Settings -> Race -> Human
3. Click EHP Values
4. Click Main Hand and see DPS differences between weapon types in particular vengeful glad items

**Expected behavior**
Sword and mace should be slightly higher than the others due to extra expertise while still below expertise softcap.

**Comment by jimmyt857** [comment]
Thanks for the report! For simplicity we keep the item menu EP values to just raw stats on the item. There are plenty of other things that don't get included, like set bonuses or trinket effects.

It's not out of the question to eventually add something like this, but even in this simple case there's a catch: for dual-wield setups the bonus expertise is only applied to 1 hand, so we can't just add the additional expertise as EP.

**Comment by gimly32** [comment]
could add a custom stat weight to weapon types similar to the pawn addon

**Comment by jimmyt857** [comment]
The point is not whether we could do it, it's about going down a rabbit-hole of adding small optimizations that also go against the design. To be clear, here are the 2 problems with adding something like this:

 - If we were to implement this, it would also make sense to start trying to compute EP values for lots of other things that are not raw stats. There are dozens of them (hundreds if you count trinkets) and it would be a lot of work to maintain for almost no benefit.
 - The goal of this suggestion would be to make the EP values in the item menu more accurate to the actual DPS gain of the items. However, those EP values are NOT intended to be used as direct measures of DPS; they are just rough estimates so that your reasonable gear options will appear near the top. The user is always intended to sim their setups because that's where actual measures of DPS come from.

**Comment by jimmyt857** [comment]
Closing this as we'll be starting the migration to wrath soon, so there won't be enough time to do this even if we wanted to.

Can re-open in wrath if it becomes an issue.

**Comment by brandofriva** [comment]
Appreciate the effort folks <3
