### ISSUE TITLE
Armor debuff numbers

### ISSUE THREAD

**Issue by Kaladryn** [wowsims/tbc#836]
**Describe the bug**
When I set the sim to 6193 in settings, I have expose and sunder on (-3075 for imp expose armor), faerie fire (-610), and curse of reck (-800) I'm left with 1708 armor. I remove executioner for testing purposes and take my total armor pen to 1708 (using +armor pen stat on top of my equipment). Now I should be capped, but if I further increase my armor pen, I am still seeing a significant dps increase and stat value. If I push armor pen up to about 2850 I start to cap, but I should be capping at 1708 with my settings. Here is the armor pen chart with values. 4 out 6 sunwell bosses are low armor btw, just for considering defaults also.

![image](https://user-images.githubusercontent.com/65414949/167020696-e9da0996-7967-4037-af0b-03af233d87cd.png)

**Comment by jimmyt857** [comment]
You'll have to provide a link to your settings. I just tried this and was not able to replicate it. A few things I'd like to note here:

 - EP results might not show as 0 because of the was they're calculated, if you're right at the cap. That's working as intended.
 - There will still be a very small boost from armor pen because the Sunder Armor and Expose Armor options are applied naturally (1 sunder stack every 1.5s, IEA at 10s). But this should be a very small DPS increase. I'm seeing ~3 dps increase from +100 armor pen beyond the cap.

**Comment by Kaladryn** [comment]
I failed to have imp expose armor selected, which accounts for the 1k armor, sorry! Awesome tool!
