### ISSUE TITLE
Shattered Sun Pendant of Might proc depends on faction

### ISSUE THREAD

**Issue by jdelvare** [wowsims/tbc#972]
Shattered Sun Pendant of Might is listed as a single item in the Neck list, although its proc is different for Aldor and Scryers players. The Settings panel does not let the user declare whether he/she is aligned with the Aldor or the Scryers, so the tool can't decide which proc to apply.

I can think of 2 ways to fix this problem. Either an Aldor/Scryers selection is offered in the Settings, in the Player section, much like the race selector. Or the Shattered Sun Pendant of Might entry gets duplicated in the Neck item list, one with the Aldor proc, one with the Scryers proc. The former solution looks cleaner to me, but would probably require a bit more more work.

**Comment by jimmyt857** [comment]
There is an Aldor/Scryer option in the Settings panel, which is only shown when one of these necklaces is equipped. It appears right under the option for Race.  ;)

**Comment by jdelvare** [comment]
Hmm, OK, didn't see that, my bad. So the feature is there but the UI is a bit misleading. I believe you should always display the faction selector regardless of the equipped items. Most users (including myself) will fill out the Settings first, and then test different gear sets, without going back to the Settings panel each time. Well, I do when I change an active trinket, because the cooldown needs to be enabled, but I did not think of doing the same when changing my necklace. Now I know, but I'm reasonably certain other users will miss it.

(On a related note about changing trinkets: I would personally appreciate if I did not actually have to go back to the Settings when replacing an active trinket with another active trinket. It seems safe and desirable to assume that the user wants to use the cooldown, defaulting to the settings used for the original trinket.)

And a minor nitpick, Aldor should be listed before Scryers in the drop down selector.

**Comment by jimmyt857** [comment]
I understand that it can be a bit hard to find because of the flow. Unfortunately, hiding it is an intentional decision we made because we don't want to commit permanent screen space to an option that is only relevant to 2 items in the game, neither of which is bis. Keeping the UI as simple as possible is deemed worth the tradeoff, if we had it on all the time we would get more questions from users about why its there at all, and it would add clutter to an already-complicated page.

Auto-swapping the trinket CDs is something I actually tried to add in the past, but ran into issues with certain edge cases. I don't remember what those are anymore but I might be able to take a look before we start migrating to wrath. We'll see though, time is tight and this wouldn't be high priority.

Aldor before Scryer makes sense, will get that changed.
